# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/instance/get_topology.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from narupa.protocol.topology import topology_pb2 as narupa_dot_protocol_dot_topology_dot_topology__pb2
from narupa.protocol import delimiter_pb2 as narupa_dot_protocol_dot_delimiter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/instance/get_topology.proto',
  package='narupa.protocol.instance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+narupa/protocol/instance/get_topology.proto\x12\x18narupa.protocol.instance\x1a\'narupa/protocol/topology/topology.proto\x1a\x1fnarupa/protocol/delimiter.proto\"\x14\n\x12GetTopologyRequest\"\x93\x01\n\x13GetTopologyResponse\x12\x13\n\x0b\x66rame_index\x18\x01 \x01(\r\x12\x38\n\x08topology\x18\x02 \x01(\x0b\x32&.narupa.protocol.topology.TopologyData\x12-\n\tdelimiter\x18\x03 \x01(\x0e\x32\x1a.narupa.protocol.Delimiterb\x06proto3')
  ,
  dependencies=[narupa_dot_protocol_dot_topology_dot_topology__pb2.DESCRIPTOR,narupa_dot_protocol_dot_delimiter__pb2.DESCRIPTOR,])




_GETTOPOLOGYREQUEST = _descriptor.Descriptor(
  name='GetTopologyRequest',
  full_name='narupa.protocol.instance.GetTopologyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=167,
)


_GETTOPOLOGYRESPONSE = _descriptor.Descriptor(
  name='GetTopologyResponse',
  full_name='narupa.protocol.instance.GetTopologyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_index', full_name='narupa.protocol.instance.GetTopologyResponse.frame_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topology', full_name='narupa.protocol.instance.GetTopologyResponse.topology', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delimiter', full_name='narupa.protocol.instance.GetTopologyResponse.delimiter', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=317,
)

_GETTOPOLOGYRESPONSE.fields_by_name['topology'].message_type = narupa_dot_protocol_dot_topology_dot_topology__pb2._TOPOLOGYDATA
_GETTOPOLOGYRESPONSE.fields_by_name['delimiter'].enum_type = narupa_dot_protocol_dot_delimiter__pb2._DELIMITER
DESCRIPTOR.message_types_by_name['GetTopologyRequest'] = _GETTOPOLOGYREQUEST
DESCRIPTOR.message_types_by_name['GetTopologyResponse'] = _GETTOPOLOGYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetTopologyRequest = _reflection.GeneratedProtocolMessageType('GetTopologyRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETTOPOLOGYREQUEST,
  __module__ = 'narupa.protocol.instance.get_topology_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.GetTopologyRequest)
  ))
_sym_db.RegisterMessage(GetTopologyRequest)

GetTopologyResponse = _reflection.GeneratedProtocolMessageType('GetTopologyResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETTOPOLOGYRESPONSE,
  __module__ = 'narupa.protocol.instance.get_topology_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.GetTopologyResponse)
  ))
_sym_db.RegisterMessage(GetTopologyResponse)


# @@protoc_insertion_point(module_scope)
