# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/instance/get_frame.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from narupa.protocol.trajectory import frame_pb2 as narupa_dot_protocol_dot_trajectory_dot_frame__pb2
from narupa.protocol import delimiter_pb2 as narupa_dot_protocol_dot_delimiter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/instance/get_frame.proto',
  package='narupa.protocol.instance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n(narupa/protocol/instance/get_frame.proto\x12\x18narupa.protocol.instance\x1a&narupa/protocol/trajectory/frame.proto\x1a\x1fnarupa/protocol/delimiter.proto\"\x11\n\x0fGetFrameRequest\"\x9b\x01\n\x10GetFrameResponse\x12\x13\n\x0b\x66rame_index\x18\x01 \x01(\r\x12\x36\n\x05\x66rame\x18\x02 \x01(\x0b\x32%.narupa.protocol.trajectory.FrameDataH\x00\x12/\n\tdelimiter\x18\x03 \x01(\x0e\x32\x1a.narupa.protocol.DelimiterH\x00\x42\t\n\x07\x63ontentb\x06proto3')
  ,
  dependencies=[narupa_dot_protocol_dot_trajectory_dot_frame__pb2.DESCRIPTOR,narupa_dot_protocol_dot_delimiter__pb2.DESCRIPTOR,])




_GETFRAMEREQUEST = _descriptor.Descriptor(
  name='GetFrameRequest',
  full_name='narupa.protocol.instance.GetFrameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=160,
)


_GETFRAMERESPONSE = _descriptor.Descriptor(
  name='GetFrameResponse',
  full_name='narupa.protocol.instance.GetFrameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_index', full_name='narupa.protocol.instance.GetFrameResponse.frame_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame', full_name='narupa.protocol.instance.GetFrameResponse.frame', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delimiter', full_name='narupa.protocol.instance.GetFrameResponse.delimiter', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='narupa.protocol.instance.GetFrameResponse.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=163,
  serialized_end=318,
)

_GETFRAMERESPONSE.fields_by_name['frame'].message_type = narupa_dot_protocol_dot_trajectory_dot_frame__pb2._FRAMEDATA
_GETFRAMERESPONSE.fields_by_name['delimiter'].enum_type = narupa_dot_protocol_dot_delimiter__pb2._DELIMITER
_GETFRAMERESPONSE.oneofs_by_name['content'].fields.append(
  _GETFRAMERESPONSE.fields_by_name['frame'])
_GETFRAMERESPONSE.fields_by_name['frame'].containing_oneof = _GETFRAMERESPONSE.oneofs_by_name['content']
_GETFRAMERESPONSE.oneofs_by_name['content'].fields.append(
  _GETFRAMERESPONSE.fields_by_name['delimiter'])
_GETFRAMERESPONSE.fields_by_name['delimiter'].containing_oneof = _GETFRAMERESPONSE.oneofs_by_name['content']
DESCRIPTOR.message_types_by_name['GetFrameRequest'] = _GETFRAMEREQUEST
DESCRIPTOR.message_types_by_name['GetFrameResponse'] = _GETFRAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetFrameRequest = _reflection.GeneratedProtocolMessageType('GetFrameRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETFRAMEREQUEST,
  __module__ = 'narupa.protocol.instance.get_frame_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.GetFrameRequest)
  ))
_sym_db.RegisterMessage(GetFrameRequest)

GetFrameResponse = _reflection.GeneratedProtocolMessageType('GetFrameResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETFRAMERESPONSE,
  __module__ = 'narupa.protocol.instance.get_frame_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.GetFrameResponse)
  ))
_sym_db.RegisterMessage(GetFrameResponse)


# @@protoc_insertion_point(module_scope)
