# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/instance/InstanceInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/instance/InstanceInfo.proto',
  package='narupa.protocol.instance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+narupa/protocol/instance/InstanceInfo.proto\x12\x18narupa.protocol.instance\"E\n\x0cInstanceInfo\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\natom_count\x18\x03 \x01(\rb\x06proto3')
)




_INSTANCEINFO = _descriptor.Descriptor(
  name='InstanceInfo',
  full_name='narupa.protocol.instance.InstanceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='narupa.protocol.instance.InstanceInfo.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='narupa.protocol.instance.InstanceInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='atom_count', full_name='narupa.protocol.instance.InstanceInfo.atom_count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['InstanceInfo'] = _INSTANCEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstanceInfo = _reflection.GeneratedProtocolMessageType('InstanceInfo', (_message.Message,), dict(
  DESCRIPTOR = _INSTANCEINFO,
  __module__ = 'narupa.protocol.instance.InstanceInfo_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.InstanceInfo)
  ))
_sym_db.RegisterMessage(InstanceInfo)


# @@protoc_insertion_point(module_scope)
