# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from narupa.protocol.lobby import lobby_pb2 as narupa_dot_protocol_dot_lobby_dot_lobby__pb2


class LobbyStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetLobbyInfo = channel.unary_unary(
        '/narupa.lobby.Lobby/GetLobbyInfo',
        request_serializer=narupa_dot_protocol_dot_lobby_dot_lobby__pb2.LobbyInfoRequest.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_lobby_dot_lobby__pb2.LobbyInfo.FromString,
        )
    self.GetServices = channel.unary_stream(
        '/narupa.lobby.Lobby/GetServices',
        request_serializer=narupa_dot_protocol_dot_lobby_dot_lobby__pb2.ServiceInfoRequest.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_lobby_dot_lobby__pb2.ServiceInfo.FromString,
        )
    self.GetRunningServices = channel.unary_stream(
        '/narupa.lobby.Lobby/GetRunningServices',
        request_serializer=narupa_dot_protocol_dot_lobby_dot_lobby__pb2.ServiceRequest.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_lobby_dot_lobby__pb2.Service.FromString,
        )


class LobbyServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetLobbyInfo(self, request, context):
    """Gets the lobby info 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetServices(self, request, context):
    """Gets the services this lobby can run.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRunningServices(self, request, context):
    """Gets the currently running services. 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LobbyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetLobbyInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetLobbyInfo,
          request_deserializer=narupa_dot_protocol_dot_lobby_dot_lobby__pb2.LobbyInfoRequest.FromString,
          response_serializer=narupa_dot_protocol_dot_lobby_dot_lobby__pb2.LobbyInfo.SerializeToString,
      ),
      'GetServices': grpc.unary_stream_rpc_method_handler(
          servicer.GetServices,
          request_deserializer=narupa_dot_protocol_dot_lobby_dot_lobby__pb2.ServiceInfoRequest.FromString,
          response_serializer=narupa_dot_protocol_dot_lobby_dot_lobby__pb2.ServiceInfo.SerializeToString,
      ),
      'GetRunningServices': grpc.unary_stream_rpc_method_handler(
          servicer.GetRunningServices,
          request_deserializer=narupa_dot_protocol_dot_lobby_dot_lobby__pb2.ServiceRequest.FromString,
          response_serializer=narupa_dot_protocol_dot_lobby_dot_lobby__pb2.Service.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'narupa.lobby.Lobby', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
