// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: chaindef.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Narupa.Protocol.Topology {

  /// <summary>Holder for reflection information generated from chaindef.proto</summary>
  public static partial class ChaindefReflection {

    #region Descriptor
    /// <summary>File descriptor for chaindef.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChaindefReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5jaGFpbmRlZi5wcm90bxIPbmFydXBhLnRvcG9sb2d5IkwKCENoYWluRGVm",
            "EhMKC2NoYWluX2luZGV4GAEgASgNEhIKCmNoYWluX25hbWUYAiABKAkSFwoP",
            "cmVzaWR1ZV9pbmRpY2VzGAMgAygNQhuqAhhOYXJ1cGEuUHJvdG9jb2wuVG9w",
            "b2xvZ3liBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Narupa.Protocol.Topology.ChainDef), global::Narupa.Protocol.Topology.ChainDef.Parser, new[]{ "ChainIndex", "ChainName", "ResidueIndices" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ChainDef : pb::IMessage<ChainDef> {
    private static readonly pb::MessageParser<ChainDef> _parser = new pb::MessageParser<ChainDef>(() => new ChainDef());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChainDef> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Narupa.Protocol.Topology.ChaindefReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChainDef() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChainDef(ChainDef other) : this() {
      chainIndex_ = other.chainIndex_;
      chainName_ = other.chainName_;
      residueIndices_ = other.residueIndices_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChainDef Clone() {
      return new ChainDef(this);
    }

    /// <summary>Field number for the "chain_index" field.</summary>
    public const int ChainIndexFieldNumber = 1;
    private uint chainIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ChainIndex {
      get { return chainIndex_; }
      set {
        chainIndex_ = value;
      }
    }

    /// <summary>Field number for the "chain_name" field.</summary>
    public const int ChainNameFieldNumber = 2;
    private string chainName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ChainName {
      get { return chainName_; }
      set {
        chainName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "residue_indices" field.</summary>
    public const int ResidueIndicesFieldNumber = 3;
    private static readonly pb::FieldCodec<uint> _repeated_residueIndices_codec
        = pb::FieldCodec.ForUInt32(26);
    private readonly pbc::RepeatedField<uint> residueIndices_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> ResidueIndices {
      get { return residueIndices_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChainDef);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChainDef other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChainIndex != other.ChainIndex) return false;
      if (ChainName != other.ChainName) return false;
      if(!residueIndices_.Equals(other.residueIndices_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ChainIndex != 0) hash ^= ChainIndex.GetHashCode();
      if (ChainName.Length != 0) hash ^= ChainName.GetHashCode();
      hash ^= residueIndices_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ChainIndex != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ChainIndex);
      }
      if (ChainName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ChainName);
      }
      residueIndices_.WriteTo(output, _repeated_residueIndices_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ChainIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChainIndex);
      }
      if (ChainName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChainName);
      }
      size += residueIndices_.CalculateSize(_repeated_residueIndices_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChainDef other) {
      if (other == null) {
        return;
      }
      if (other.ChainIndex != 0) {
        ChainIndex = other.ChainIndex;
      }
      if (other.ChainName.Length != 0) {
        ChainName = other.ChainName;
      }
      residueIndices_.Add(other.residueIndices_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChainIndex = input.ReadUInt32();
            break;
          }
          case 18: {
            ChainName = input.ReadString();
            break;
          }
          case 26:
          case 24: {
            residueIndices_.AddEntriesFrom(input, _repeated_residueIndices_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
