// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: residuedef.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Narupa.Protocol.Topology {

  /// <summary>Holder for reflection information generated from residuedef.proto</summary>
  public static partial class ResiduedefReflection {

    #region Descriptor
    /// <summary>File descriptor for residuedef.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResiduedefReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChByZXNpZHVlZGVmLnByb3RvEg9uYXJ1cGEudG9wb2xvZ3kiTwoKUmVzaWR1",
            "ZURlZhIVCg1yZXNpZHVlX2luZGV4GAEgASgNEhQKDHJlc2lkdWVfbmFtZRgC",
            "IAEoCRIUCgxhdG9tX2luZGljZXMYAyADKA1CG6oCGE5hcnVwYS5Qcm90b2Nv",
            "bC5Ub3BvbG9neWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Narupa.Protocol.Topology.ResidueDef), global::Narupa.Protocol.Topology.ResidueDef.Parser, new[]{ "ResidueIndex", "ResidueName", "AtomIndices" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ResidueDef : pb::IMessage<ResidueDef> {
    private static readonly pb::MessageParser<ResidueDef> _parser = new pb::MessageParser<ResidueDef>(() => new ResidueDef());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResidueDef> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Narupa.Protocol.Topology.ResiduedefReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResidueDef() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResidueDef(ResidueDef other) : this() {
      residueIndex_ = other.residueIndex_;
      residueName_ = other.residueName_;
      atomIndices_ = other.atomIndices_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResidueDef Clone() {
      return new ResidueDef(this);
    }

    /// <summary>Field number for the "residue_index" field.</summary>
    public const int ResidueIndexFieldNumber = 1;
    private uint residueIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ResidueIndex {
      get { return residueIndex_; }
      set {
        residueIndex_ = value;
      }
    }

    /// <summary>Field number for the "residue_name" field.</summary>
    public const int ResidueNameFieldNumber = 2;
    private string residueName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ResidueName {
      get { return residueName_; }
      set {
        residueName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "atom_indices" field.</summary>
    public const int AtomIndicesFieldNumber = 3;
    private static readonly pb::FieldCodec<uint> _repeated_atomIndices_codec
        = pb::FieldCodec.ForUInt32(26);
    private readonly pbc::RepeatedField<uint> atomIndices_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> AtomIndices {
      get { return atomIndices_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResidueDef);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResidueDef other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResidueIndex != other.ResidueIndex) return false;
      if (ResidueName != other.ResidueName) return false;
      if(!atomIndices_.Equals(other.atomIndices_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResidueIndex != 0) hash ^= ResidueIndex.GetHashCode();
      if (ResidueName.Length != 0) hash ^= ResidueName.GetHashCode();
      hash ^= atomIndices_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResidueIndex != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ResidueIndex);
      }
      if (ResidueName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ResidueName);
      }
      atomIndices_.WriteTo(output, _repeated_atomIndices_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResidueIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ResidueIndex);
      }
      if (ResidueName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResidueName);
      }
      size += atomIndices_.CalculateSize(_repeated_atomIndices_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResidueDef other) {
      if (other == null) {
        return;
      }
      if (other.ResidueIndex != 0) {
        ResidueIndex = other.ResidueIndex;
      }
      if (other.ResidueName.Length != 0) {
        ResidueName = other.ResidueName;
      }
      atomIndices_.Add(other.atomIndices_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResidueIndex = input.ReadUInt32();
            break;
          }
          case 18: {
            ResidueName = input.ReadString();
            break;
          }
          case 26:
          case 24: {
            atomIndices_.AddEntriesFrom(input, _repeated_atomIndices_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
