// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: topology.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Narupa.Protocol.Topology {

  /// <summary>Holder for reflection information generated from topology.proto</summary>
  public static partial class TopologyReflection {

    #region Descriptor
    /// <summary>File descriptor for topology.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TopologyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg50b3BvbG9neS5wcm90bxIPbmFydXBhLnRvcG9sb2d5Gg5jaGFpbmRlZi5w",
            "cm90bxoQcmVzaWR1ZWRlZi5wcm90bxoNYXRvbWRlZi5wcm90bxoNYm9uZGRl",
            "Zi5wcm90byLFAQoIVG9wb2xvZ3kSDQoFZnJhbWUYBSABKA0SJwoFYXRvbXMY",
            "ASADKAsyGC5uYXJ1cGEudG9wb2xvZ3kuQXRvbURlZhInCgVib25kcxgCIAMo",
            "CzIYLm5hcnVwYS50b3BvbG9neS5Cb25kRGVmEi0KCHJlc2lkdWVzGAMgAygL",
            "MhsubmFydXBhLnRvcG9sb2d5LlJlc2lkdWVEZWYSKQoGY2hhaW5zGAQgAygL",
            "MhkubmFydXBhLnRvcG9sb2d5LkNoYWluRGVmQhuqAhhOYXJ1cGEuUHJvdG9j",
            "b2wuVG9wb2xvZ3liBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Narupa.Protocol.Topology.ChaindefReflection.Descriptor, global::Narupa.Protocol.Topology.ResiduedefReflection.Descriptor, global::Narupa.Protocol.Topology.AtomdefReflection.Descriptor, global::Narupa.Protocol.Topology.BonddefReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Narupa.Protocol.Topology.Topology), global::Narupa.Protocol.Topology.Topology.Parser, new[]{ "Frame", "Atoms", "Bonds", "Residues", "Chains" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Topology : pb::IMessage<Topology> {
    private static readonly pb::MessageParser<Topology> _parser = new pb::MessageParser<Topology>(() => new Topology());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Topology> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Narupa.Protocol.Topology.TopologyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Topology() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Topology(Topology other) : this() {
      frame_ = other.frame_;
      atoms_ = other.atoms_.Clone();
      bonds_ = other.bonds_.Clone();
      residues_ = other.residues_.Clone();
      chains_ = other.chains_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Topology Clone() {
      return new Topology(this);
    }

    /// <summary>Field number for the "frame" field.</summary>
    public const int FrameFieldNumber = 5;
    private uint frame_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Frame {
      get { return frame_; }
      set {
        frame_ = value;
      }
    }

    /// <summary>Field number for the "atoms" field.</summary>
    public const int AtomsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Narupa.Protocol.Topology.AtomDef> _repeated_atoms_codec
        = pb::FieldCodec.ForMessage(10, global::Narupa.Protocol.Topology.AtomDef.Parser);
    private readonly pbc::RepeatedField<global::Narupa.Protocol.Topology.AtomDef> atoms_ = new pbc::RepeatedField<global::Narupa.Protocol.Topology.AtomDef>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Narupa.Protocol.Topology.AtomDef> Atoms {
      get { return atoms_; }
    }

    /// <summary>Field number for the "bonds" field.</summary>
    public const int BondsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Narupa.Protocol.Topology.BondDef> _repeated_bonds_codec
        = pb::FieldCodec.ForMessage(18, global::Narupa.Protocol.Topology.BondDef.Parser);
    private readonly pbc::RepeatedField<global::Narupa.Protocol.Topology.BondDef> bonds_ = new pbc::RepeatedField<global::Narupa.Protocol.Topology.BondDef>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Narupa.Protocol.Topology.BondDef> Bonds {
      get { return bonds_; }
    }

    /// <summary>Field number for the "residues" field.</summary>
    public const int ResiduesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Narupa.Protocol.Topology.ResidueDef> _repeated_residues_codec
        = pb::FieldCodec.ForMessage(26, global::Narupa.Protocol.Topology.ResidueDef.Parser);
    private readonly pbc::RepeatedField<global::Narupa.Protocol.Topology.ResidueDef> residues_ = new pbc::RepeatedField<global::Narupa.Protocol.Topology.ResidueDef>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Narupa.Protocol.Topology.ResidueDef> Residues {
      get { return residues_; }
    }

    /// <summary>Field number for the "chains" field.</summary>
    public const int ChainsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Narupa.Protocol.Topology.ChainDef> _repeated_chains_codec
        = pb::FieldCodec.ForMessage(34, global::Narupa.Protocol.Topology.ChainDef.Parser);
    private readonly pbc::RepeatedField<global::Narupa.Protocol.Topology.ChainDef> chains_ = new pbc::RepeatedField<global::Narupa.Protocol.Topology.ChainDef>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Narupa.Protocol.Topology.ChainDef> Chains {
      get { return chains_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Topology);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Topology other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Frame != other.Frame) return false;
      if(!atoms_.Equals(other.atoms_)) return false;
      if(!bonds_.Equals(other.bonds_)) return false;
      if(!residues_.Equals(other.residues_)) return false;
      if(!chains_.Equals(other.chains_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Frame != 0) hash ^= Frame.GetHashCode();
      hash ^= atoms_.GetHashCode();
      hash ^= bonds_.GetHashCode();
      hash ^= residues_.GetHashCode();
      hash ^= chains_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      atoms_.WriteTo(output, _repeated_atoms_codec);
      bonds_.WriteTo(output, _repeated_bonds_codec);
      residues_.WriteTo(output, _repeated_residues_codec);
      chains_.WriteTo(output, _repeated_chains_codec);
      if (Frame != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Frame);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Frame != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Frame);
      }
      size += atoms_.CalculateSize(_repeated_atoms_codec);
      size += bonds_.CalculateSize(_repeated_bonds_codec);
      size += residues_.CalculateSize(_repeated_residues_codec);
      size += chains_.CalculateSize(_repeated_chains_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Topology other) {
      if (other == null) {
        return;
      }
      if (other.Frame != 0) {
        Frame = other.Frame;
      }
      atoms_.Add(other.atoms_);
      bonds_.Add(other.bonds_);
      residues_.Add(other.residues_);
      chains_.Add(other.chains_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            atoms_.AddEntriesFrom(input, _repeated_atoms_codec);
            break;
          }
          case 18: {
            bonds_.AddEntriesFrom(input, _repeated_bonds_codec);
            break;
          }
          case 26: {
            residues_.AddEntriesFrom(input, _repeated_residues_codec);
            break;
          }
          case 34: {
            chains_.AddEntriesFrom(input, _repeated_chains_codec);
            break;
          }
          case 40: {
            Frame = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
