# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/lobby/lobby.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/lobby/lobby.proto',
  package='narupa.lobby',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!narupa/protocol/lobby/lobby.proto\x12\x0cnarupa.lobby\"\x12\n\x10LobbyInfoRequest\"\x14\n\x12ServiceInfoRequest\"\x10\n\x0eServiceRequest\",\n\x0bServiceInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"a\n\x07Service\x12\'\n\x04info\x18\x01 \x01(\x0b\x32\x19.narupa.lobby.ServiceInfo\x12\x12\n\nidentifier\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\"&\n\tLobbyInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t2\xf1\x01\n\x05Lobby\x12I\n\x0cGetLobbyInfo\x12\x1e.narupa.lobby.LobbyInfoRequest\x1a\x17.narupa.lobby.LobbyInfo\"\x00\x12N\n\x0bGetServices\x12 .narupa.lobby.ServiceInfoRequest\x1a\x19.narupa.lobby.ServiceInfo\"\x00\x30\x01\x12M\n\x12GetRunningServices\x12\x1c.narupa.lobby.ServiceRequest\x1a\x15.narupa.lobby.Service\"\x00\x30\x01\x62\x06proto3')
)




_LOBBYINFOREQUEST = _descriptor.Descriptor(
  name='LobbyInfoRequest',
  full_name='narupa.lobby.LobbyInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=69,
)


_SERVICEINFOREQUEST = _descriptor.Descriptor(
  name='ServiceInfoRequest',
  full_name='narupa.lobby.ServiceInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=91,
)


_SERVICEREQUEST = _descriptor.Descriptor(
  name='ServiceRequest',
  full_name='narupa.lobby.ServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=109,
)


_SERVICEINFO = _descriptor.Descriptor(
  name='ServiceInfo',
  full_name='narupa.lobby.ServiceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='narupa.lobby.ServiceInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='narupa.lobby.ServiceInfo.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=155,
)


_SERVICE = _descriptor.Descriptor(
  name='Service',
  full_name='narupa.lobby.Service',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='narupa.lobby.Service.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identifier', full_name='narupa.lobby.Service.identifier', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='narupa.lobby.Service.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='narupa.lobby.Service.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=254,
)


_LOBBYINFO = _descriptor.Descriptor(
  name='LobbyInfo',
  full_name='narupa.lobby.LobbyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='narupa.lobby.LobbyInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='narupa.lobby.LobbyInfo.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=294,
)

_SERVICE.fields_by_name['info'].message_type = _SERVICEINFO
DESCRIPTOR.message_types_by_name['LobbyInfoRequest'] = _LOBBYINFOREQUEST
DESCRIPTOR.message_types_by_name['ServiceInfoRequest'] = _SERVICEINFOREQUEST
DESCRIPTOR.message_types_by_name['ServiceRequest'] = _SERVICEREQUEST
DESCRIPTOR.message_types_by_name['ServiceInfo'] = _SERVICEINFO
DESCRIPTOR.message_types_by_name['Service'] = _SERVICE
DESCRIPTOR.message_types_by_name['LobbyInfo'] = _LOBBYINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LobbyInfoRequest = _reflection.GeneratedProtocolMessageType('LobbyInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOBBYINFOREQUEST,
  __module__ = 'narupa.protocol.lobby.lobby_pb2'
  # @@protoc_insertion_point(class_scope:narupa.lobby.LobbyInfoRequest)
  ))
_sym_db.RegisterMessage(LobbyInfoRequest)

ServiceInfoRequest = _reflection.GeneratedProtocolMessageType('ServiceInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _SERVICEINFOREQUEST,
  __module__ = 'narupa.protocol.lobby.lobby_pb2'
  # @@protoc_insertion_point(class_scope:narupa.lobby.ServiceInfoRequest)
  ))
_sym_db.RegisterMessage(ServiceInfoRequest)

ServiceRequest = _reflection.GeneratedProtocolMessageType('ServiceRequest', (_message.Message,), dict(
  DESCRIPTOR = _SERVICEREQUEST,
  __module__ = 'narupa.protocol.lobby.lobby_pb2'
  # @@protoc_insertion_point(class_scope:narupa.lobby.ServiceRequest)
  ))
_sym_db.RegisterMessage(ServiceRequest)

ServiceInfo = _reflection.GeneratedProtocolMessageType('ServiceInfo', (_message.Message,), dict(
  DESCRIPTOR = _SERVICEINFO,
  __module__ = 'narupa.protocol.lobby.lobby_pb2'
  # @@protoc_insertion_point(class_scope:narupa.lobby.ServiceInfo)
  ))
_sym_db.RegisterMessage(ServiceInfo)

Service = _reflection.GeneratedProtocolMessageType('Service', (_message.Message,), dict(
  DESCRIPTOR = _SERVICE,
  __module__ = 'narupa.protocol.lobby.lobby_pb2'
  # @@protoc_insertion_point(class_scope:narupa.lobby.Service)
  ))
_sym_db.RegisterMessage(Service)

LobbyInfo = _reflection.GeneratedProtocolMessageType('LobbyInfo', (_message.Message,), dict(
  DESCRIPTOR = _LOBBYINFO,
  __module__ = 'narupa.protocol.lobby.lobby_pb2'
  # @@protoc_insertion_point(class_scope:narupa.lobby.LobbyInfo)
  ))
_sym_db.RegisterMessage(LobbyInfo)



_LOBBY = _descriptor.ServiceDescriptor(
  name='Lobby',
  full_name='narupa.lobby.Lobby',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=297,
  serialized_end=538,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLobbyInfo',
    full_name='narupa.lobby.Lobby.GetLobbyInfo',
    index=0,
    containing_service=None,
    input_type=_LOBBYINFOREQUEST,
    output_type=_LOBBYINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetServices',
    full_name='narupa.lobby.Lobby.GetServices',
    index=1,
    containing_service=None,
    input_type=_SERVICEINFOREQUEST,
    output_type=_SERVICEINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRunningServices',
    full_name='narupa.lobby.Lobby.GetRunningServices',
    index=2,
    containing_service=None,
    input_type=_SERVICEREQUEST,
    output_type=_SERVICE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOBBY)

DESCRIPTOR.services_by_name['Lobby'] = _LOBBY

# @@protoc_insertion_point(module_scope)
