package:
  name: nanover-server
  version: {{ NANOVER_BUILD_VERSION }}

source:
  path: ../

build:
  noarch: python
  number: 0
  entry_points:
    - nanover-omni = nanover.omni.cli:main
    - nanover-record = nanover.omni.recorder_cli:main
    - nanover-essd-list = nanover.essd.list_cli:main
    - nanover-multiplayer = nanover.multiplayer.cli:main
    - nanover-dump-state = nanover.recording.cli.dump_cli:main
    - nanover-split-recording = nanover.recording.cli.split_cli:main
    - nanover-check-recording = nanover.recording.cli.check_cli:main

requirements:
  build:
    - python >={{ MIN_PYTHON_VERSION }}
    - setuptools
    - grpcio-tools
  run:
    - python >={{ MIN_PYTHON_VERSION }}
    - netifaces
    - grpcio
    - numpy
    - typing-extensions
    - protobuf
    - attrs
    - openmm
    - ase >=3.21
    - mdanalysis
    - nglview

about:
  home: {{ NANOVER_DOC_URL }}
  license: MIT
  license_file: {{ NANOVER_LICENSE_PATH }}
  summary: Python servers for NanoVer.
  description: |
    NanoVer is a framework for interactive molecular dynamics simulation in
    virtual reality. This package cause all the python servers to be installed.
  doc_url: {{ NANOVER_DOC_URL }}
  dev_url: {{ NANOVER_REPO_URL }}