# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/topology/AtomInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/topology/AtomInfo.proto',
  package='narupa.protocol.topology',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'narupa/protocol/topology/AtomInfo.proto\x12\x18narupa.protocol.topology\"T\n\x08\x41tomInfo\x12\x12\n\natom_index\x18\x01 \x01(\r\x12\x0f\n\x07\x65lement\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x15\n\rresidue_index\x18\x04 \x01(\rb\x06proto3')
)




_ATOMINFO = _descriptor.Descriptor(
  name='AtomInfo',
  full_name='narupa.protocol.topology.AtomInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='atom_index', full_name='narupa.protocol.topology.AtomInfo.atom_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='element', full_name='narupa.protocol.topology.AtomInfo.element', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='narupa.protocol.topology.AtomInfo.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='residue_index', full_name='narupa.protocol.topology.AtomInfo.residue_index', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['AtomInfo'] = _ATOMINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AtomInfo = _reflection.GeneratedProtocolMessageType('AtomInfo', (_message.Message,), dict(
  DESCRIPTOR = _ATOMINFO,
  __module__ = 'narupa.protocol.topology.AtomInfo_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.topology.AtomInfo)
  ))
_sym_db.RegisterMessage(AtomInfo)


# @@protoc_insertion_point(module_scope)
