# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/topology/BondPair.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/topology/BondPair.proto',
  package='narupa.protocol.topology',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'narupa/protocol/topology/BondPair.proto\x12\x18narupa.protocol.topology\" \n\x08\x42ondPair\x12\t\n\x01\x41\x18\x01 \x01(\r\x12\t\n\x01\x42\x18\x02 \x01(\rb\x06proto3')
)




_BONDPAIR = _descriptor.Descriptor(
  name='BondPair',
  full_name='narupa.protocol.topology.BondPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='A', full_name='narupa.protocol.topology.BondPair.A', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='B', full_name='narupa.protocol.topology.BondPair.B', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['BondPair'] = _BONDPAIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BondPair = _reflection.GeneratedProtocolMessageType('BondPair', (_message.Message,), dict(
  DESCRIPTOR = _BONDPAIR,
  __module__ = 'narupa.protocol.topology.BondPair_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.topology.BondPair)
  ))
_sym_db.RegisterMessage(BondPair)


# @@protoc_insertion_point(module_scope)
