# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/topology/ChainInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/topology/ChainInfo.proto',
  package='narupa.protocol.topology',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n(narupa/protocol/topology/ChainInfo.proto\x12\x18narupa.protocol.topology\".\n\tChainInfo\x12\x13\n\x0b\x63hain_index\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\tb\x06proto3')
)




_CHAININFO = _descriptor.Descriptor(
  name='ChainInfo',
  full_name='narupa.protocol.topology.ChainInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chain_index', full_name='narupa.protocol.topology.ChainInfo.chain_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='narupa.protocol.topology.ChainInfo.name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['ChainInfo'] = _CHAININFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChainInfo = _reflection.GeneratedProtocolMessageType('ChainInfo', (_message.Message,), dict(
  DESCRIPTOR = _CHAININFO,
  __module__ = 'narupa.protocol.topology.ChainInfo_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.topology.ChainInfo)
  ))
_sym_db.RegisterMessage(ChainInfo)


# @@protoc_insertion_point(module_scope)
