# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from narupa.protocol.imd import imd_pb2 as narupa_dot_protocol_dot_imd_dot_imd__pb2
from narupa.protocol.instance import get_frame_pb2 as narupa_dot_protocol_dot_instance_dot_get__frame__pb2
from narupa.protocol.instance import get_topology_pb2 as narupa_dot_protocol_dot_instance_dot_get__topology__pb2


class InteractiveMolecularDynamicsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SubscribeTopology = channel.unary_stream(
        '/narupa.protocol.imd.InteractiveMolecularDynamics/SubscribeTopology',
        request_serializer=narupa_dot_protocol_dot_instance_dot_get__topology__pb2.GetTopologyRequest.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_instance_dot_get__topology__pb2.GetTopologyResponse.FromString,
        )
    self.SubscribeFrame = channel.unary_stream(
        '/narupa.protocol.imd.InteractiveMolecularDynamics/SubscribeFrame',
        request_serializer=narupa_dot_protocol_dot_instance_dot_get__frame__pb2.GetFrameRequest.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_instance_dot_get__frame__pb2.GetFrameResponse.FromString,
        )
    self.PublishInteractions = channel.stream_unary(
        '/narupa.protocol.imd.InteractiveMolecularDynamics/PublishInteractions',
        request_serializer=narupa_dot_protocol_dot_imd_dot_imd__pb2.Interaction.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_imd_dot_imd__pb2.InteractionReply.FromString,
        )


class InteractiveMolecularDynamicsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SubscribeTopology(self, request, context):
    """Subscribe to topology. 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubscribeFrame(self, request, context):
    """Subscribe to MD frames. 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PublishInteractions(self, request_iterator, context):
    """Publish interactions.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InteractiveMolecularDynamicsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SubscribeTopology': grpc.unary_stream_rpc_method_handler(
          servicer.SubscribeTopology,
          request_deserializer=narupa_dot_protocol_dot_instance_dot_get__topology__pb2.GetTopologyRequest.FromString,
          response_serializer=narupa_dot_protocol_dot_instance_dot_get__topology__pb2.GetTopologyResponse.SerializeToString,
      ),
      'SubscribeFrame': grpc.unary_stream_rpc_method_handler(
          servicer.SubscribeFrame,
          request_deserializer=narupa_dot_protocol_dot_instance_dot_get__frame__pb2.GetFrameRequest.FromString,
          response_serializer=narupa_dot_protocol_dot_instance_dot_get__frame__pb2.GetFrameResponse.SerializeToString,
      ),
      'PublishInteractions': grpc.stream_unary_rpc_method_handler(
          servicer.PublishInteractions,
          request_deserializer=narupa_dot_protocol_dot_imd_dot_imd__pb2.Interaction.FromString,
          response_serializer=narupa_dot_protocol_dot_imd_dot_imd__pb2.InteractionReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'narupa.protocol.imd.InteractiveMolecularDynamics', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
