# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/renderer/camera_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/renderer/camera_service.proto',
  package='narupa.protocol.renderer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n-narupa/protocol/renderer/camera_service.proto\x12\x18narupa.protocol.renderer\x1a\x1cgoogle/protobuf/struct.proto\"N\n\x13\x43reateCameraRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\nproperties\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"\"\n\x14\x43reateCameraResponse\x12\n\n\x02id\x18\x01 \x01(\t\"N\n\x13UpdateCameraRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\nproperties\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"\"\n\x14UpdateCameraResponse\x12\n\n\x02id\x18\x01 \x01(\t2\xed\x01\n\rCameraService\x12m\n\x0c\x43reateCamera\x12-.narupa.protocol.renderer.CreateCameraRequest\x1a..narupa.protocol.renderer.CreateCameraResponse\x12m\n\x0cUpdateCamera\x12-.narupa.protocol.renderer.UpdateCameraRequest\x1a..narupa.protocol.renderer.UpdateCameraResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_CREATECAMERAREQUEST = _descriptor.Descriptor(
  name='CreateCameraRequest',
  full_name='narupa.protocol.renderer.CreateCameraRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='narupa.protocol.renderer.CreateCameraRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='narupa.protocol.renderer.CreateCameraRequest.properties', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=183,
)


_CREATECAMERARESPONSE = _descriptor.Descriptor(
  name='CreateCameraResponse',
  full_name='narupa.protocol.renderer.CreateCameraResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='narupa.protocol.renderer.CreateCameraResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=219,
)


_UPDATECAMERAREQUEST = _descriptor.Descriptor(
  name='UpdateCameraRequest',
  full_name='narupa.protocol.renderer.UpdateCameraRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='narupa.protocol.renderer.UpdateCameraRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='narupa.protocol.renderer.UpdateCameraRequest.properties', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=299,
)


_UPDATECAMERARESPONSE = _descriptor.Descriptor(
  name='UpdateCameraResponse',
  full_name='narupa.protocol.renderer.UpdateCameraResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='narupa.protocol.renderer.UpdateCameraResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=335,
)

_CREATECAMERAREQUEST.fields_by_name['properties'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_UPDATECAMERAREQUEST.fields_by_name['properties'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['CreateCameraRequest'] = _CREATECAMERAREQUEST
DESCRIPTOR.message_types_by_name['CreateCameraResponse'] = _CREATECAMERARESPONSE
DESCRIPTOR.message_types_by_name['UpdateCameraRequest'] = _UPDATECAMERAREQUEST
DESCRIPTOR.message_types_by_name['UpdateCameraResponse'] = _UPDATECAMERARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateCameraRequest = _reflection.GeneratedProtocolMessageType('CreateCameraRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATECAMERAREQUEST,
  __module__ = 'narupa.protocol.renderer.camera_service_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.renderer.CreateCameraRequest)
  ))
_sym_db.RegisterMessage(CreateCameraRequest)

CreateCameraResponse = _reflection.GeneratedProtocolMessageType('CreateCameraResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATECAMERARESPONSE,
  __module__ = 'narupa.protocol.renderer.camera_service_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.renderer.CreateCameraResponse)
  ))
_sym_db.RegisterMessage(CreateCameraResponse)

UpdateCameraRequest = _reflection.GeneratedProtocolMessageType('UpdateCameraRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATECAMERAREQUEST,
  __module__ = 'narupa.protocol.renderer.camera_service_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.renderer.UpdateCameraRequest)
  ))
_sym_db.RegisterMessage(UpdateCameraRequest)

UpdateCameraResponse = _reflection.GeneratedProtocolMessageType('UpdateCameraResponse', (_message.Message,), dict(
  DESCRIPTOR = _UPDATECAMERARESPONSE,
  __module__ = 'narupa.protocol.renderer.camera_service_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.renderer.UpdateCameraResponse)
  ))
_sym_db.RegisterMessage(UpdateCameraResponse)



_CAMERASERVICE = _descriptor.ServiceDescriptor(
  name='CameraService',
  full_name='narupa.protocol.renderer.CameraService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=338,
  serialized_end=575,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateCamera',
    full_name='narupa.protocol.renderer.CameraService.CreateCamera',
    index=0,
    containing_service=None,
    input_type=_CREATECAMERAREQUEST,
    output_type=_CREATECAMERARESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateCamera',
    full_name='narupa.protocol.renderer.CameraService.UpdateCamera',
    index=1,
    containing_service=None,
    input_type=_UPDATECAMERAREQUEST,
    output_type=_UPDATECAMERARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAMERASERVICE)

DESCRIPTOR.services_by_name['CameraService'] = _CAMERASERVICE

# @@protoc_insertion_point(module_scope)
