# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from narupa.protocol.renderer import camera_service_pb2 as narupa_dot_protocol_dot_renderer_dot_camera__service__pb2


class CameraServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateCamera = channel.unary_unary(
        '/narupa.protocol.renderer.CameraService/CreateCamera',
        request_serializer=narupa_dot_protocol_dot_renderer_dot_camera__service__pb2.CreateCameraRequest.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_renderer_dot_camera__service__pb2.CreateCameraResponse.FromString,
        )
    self.UpdateCamera = channel.unary_unary(
        '/narupa.protocol.renderer.CameraService/UpdateCamera',
        request_serializer=narupa_dot_protocol_dot_renderer_dot_camera__service__pb2.UpdateCameraRequest.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_renderer_dot_camera__service__pb2.UpdateCameraResponse.FromString,
        )


class CameraServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateCamera(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateCamera(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CameraServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateCamera': grpc.unary_unary_rpc_method_handler(
          servicer.CreateCamera,
          request_deserializer=narupa_dot_protocol_dot_renderer_dot_camera__service__pb2.CreateCameraRequest.FromString,
          response_serializer=narupa_dot_protocol_dot_renderer_dot_camera__service__pb2.CreateCameraResponse.SerializeToString,
      ),
      'UpdateCamera': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateCamera,
          request_deserializer=narupa_dot_protocol_dot_renderer_dot_camera__service__pb2.UpdateCameraRequest.FromString,
          response_serializer=narupa_dot_protocol_dot_renderer_dot_camera__service__pb2.UpdateCameraResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'narupa.protocol.renderer.CameraService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
