# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/renderer/renderer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/renderer/renderer.proto',
  package='narupa.protocol.renderer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'narupa/protocol/renderer/renderer.proto\x12\x18narupa.protocol.renderer\"/\n\x1bRunGraphicsBenchmarkRequest\x12\x10\n\x08\x64uration\x18\x01 \x01(\x02\"2\n\x1cRunGraphicsBenchmarkResponse\x12\x12\n\naverageFps\x18\x01 \x01(\x02\x32\x9a\x01\n\x10RendererProvider\x12\x85\x01\n\x14RunGraphicsBenchmark\x12\x35.narupa.protocol.renderer.RunGraphicsBenchmarkRequest\x1a\x36.narupa.protocol.renderer.RunGraphicsBenchmarkResponseb\x06proto3')
)




_RUNGRAPHICSBENCHMARKREQUEST = _descriptor.Descriptor(
  name='RunGraphicsBenchmarkRequest',
  full_name='narupa.protocol.renderer.RunGraphicsBenchmarkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='narupa.protocol.renderer.RunGraphicsBenchmarkRequest.duration', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=116,
)


_RUNGRAPHICSBENCHMARKRESPONSE = _descriptor.Descriptor(
  name='RunGraphicsBenchmarkResponse',
  full_name='narupa.protocol.renderer.RunGraphicsBenchmarkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='averageFps', full_name='narupa.protocol.renderer.RunGraphicsBenchmarkResponse.averageFps', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=168,
)

DESCRIPTOR.message_types_by_name['RunGraphicsBenchmarkRequest'] = _RUNGRAPHICSBENCHMARKREQUEST
DESCRIPTOR.message_types_by_name['RunGraphicsBenchmarkResponse'] = _RUNGRAPHICSBENCHMARKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunGraphicsBenchmarkRequest = _reflection.GeneratedProtocolMessageType('RunGraphicsBenchmarkRequest', (_message.Message,), dict(
  DESCRIPTOR = _RUNGRAPHICSBENCHMARKREQUEST,
  __module__ = 'narupa.protocol.renderer.renderer_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.renderer.RunGraphicsBenchmarkRequest)
  ))
_sym_db.RegisterMessage(RunGraphicsBenchmarkRequest)

RunGraphicsBenchmarkResponse = _reflection.GeneratedProtocolMessageType('RunGraphicsBenchmarkResponse', (_message.Message,), dict(
  DESCRIPTOR = _RUNGRAPHICSBENCHMARKRESPONSE,
  __module__ = 'narupa.protocol.renderer.renderer_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.renderer.RunGraphicsBenchmarkResponse)
  ))
_sym_db.RegisterMessage(RunGraphicsBenchmarkResponse)



_RENDERERPROVIDER = _descriptor.ServiceDescriptor(
  name='RendererProvider',
  full_name='narupa.protocol.renderer.RendererProvider',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=171,
  serialized_end=325,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunGraphicsBenchmark',
    full_name='narupa.protocol.renderer.RendererProvider.RunGraphicsBenchmark',
    index=0,
    containing_service=None,
    input_type=_RUNGRAPHICSBENCHMARKREQUEST,
    output_type=_RUNGRAPHICSBENCHMARKRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RENDERERPROVIDER)

DESCRIPTOR.services_by_name['RendererProvider'] = _RENDERERPROVIDER

# @@protoc_insertion_point(module_scope)
