from typing import Protocol
from . import AppServer


class Simulation(Protocol):
    name: str

    def load(self): ...
    def reset(self, app_server: AppServer): ...
    def advance_by_one_step(self): ...
    def advance_by_seconds(self, dt: float): ...
