from io import TextIOWrapper
from os import PathLike
from typing import Any, BinaryIO
from zipfile import ZIP_DEFLATED, ZipFile

from openmm import CustomExternalForce, Platform, XmlSerializer
from openmm.app import PDBxFile, Simulation

from nanover.openmm.imd import populate_imd_force


def bundle_openmm_simulation(
    simulation: Simulation,
    *,
    outfile: BinaryIO | PathLike[str] | str,
    include_state = False,
    pbc_wrapping = False,
) -> None:
    """
    Bundle an OpenMM simulation into zip archive.

    :param simulation: The simulation to bundle.
    :param outfile: A file object or path to write the bundle zip to.
    :param include_state: Include the present state of the simulation in the bundle.
    :param pbc_wrapping: Wrap atom positions with periodic boundary conditions before bundling.
    """

    with ZipFile(outfile, mode="w", compression=ZIP_DEFLATED) as bundle:
        bundle.writestr(
            "README.txt",
            "OpenMM bundle generated by NanoVer",
        )

        positions = simulation.context.getState(
            getPositions=True,
            enforcePeriodicBox=pbc_wrapping,
        ).getPositions()

        with TextIOWrapper(
            bundle.open("topology.pdbx", mode="w"),
            encoding="utf8"
        ) as topology:
            PDBxFile.writeFile(
                topology=simulation.topology,
                positions=positions,
                file=topology,
            )

        _write_zipfile_xml(bundle, "system.xml", simulation.system)
        _write_zipfile_xml(bundle, "integrator.xml", simulation.integrator)

        if include_state:
            _write_zipfile_xml(
                bundle,
                "state.xml",
                simulation.context.getState(
                    getVelocities=True,
                    getParameters=True,
                    getIntegratorParameters=True,
                    enforcePeriodicBox=pbc_wrapping,
                ),
            )


def unbundle_openmm_simulation(
    bundle_file: BinaryIO | PathLike[str] | str,
    *,
    imd_force: CustomExternalForce | None = None,
    ignore_state=False,
    platform_name: str | None = None,
) -> Simulation:
    """
    Create an OpenMM simulation from a zip archive.

    :param bundle_file: The content of an XML file as a string.
    :param imd_force: Optionally, an imd force to populate and add to the
        system. The force must be created by
        :func:`nanover.openmm.potentials.create_imd_force`.
    :param ignore_state: Ignore serialized state when present.
    :param platform_name: Explicit platform to use for OpenMM.
    """

    with ZipFile(bundle_file) as bundle:
        with TextIOWrapper(bundle.open("topology.pdbx")) as pdbfile:
            pdb = PDBxFile(pdbfile)

        system = _read_zipfile_xml(bundle, "system.xml")
        integrator = _read_zipfile_xml(bundle, "integrator.xml")
        state = _read_zipfile_xml(bundle, "state.xml")

    if imd_force is not None:
        populate_imd_force(imd_force, system)
        system.addForce(imd_force)

    if platform_name is not None:
        platform = Platform.getPlatformByName(platform_name)
    else:
        platform = None

    simulation = Simulation(
        topology=pdb.topology,
        system=system,
        integrator=integrator,
        platform=platform,
    )
    simulation.context.setPositions(pdb.positions)

    if state and not ignore_state:
        simulation.context.setState(state)

    return simulation


def _read_zipfile_xml(zipfile: ZipFile, filename: str) -> Any:
    try:
        with TextIOWrapper(zipfile.open(filename)) as infile:
            return XmlSerializer.deserialize(infile.read())
    except KeyError:
        return None


def _write_zipfile_xml(zipfile: ZipFile, filename: str, object: Any) -> None:
    zipfile.writestr(filename, XmlSerializer.serialize(object))
