package:
  name: nanover-core
  version: {{ os.environ["NANOVER_BUILD_VERSION"] }}

source:
  path: ../

build:
  noarch: python
  number: 0
  entry_points:
    - nanover-multiplayer = nanover.multiplayer.cli:main
    - nanover-record = nanover.recording.recorder_cli:main

requirements:
  build:
    - python >={{ MIN_PYTHON_VERSION }}
    - setuptools
    - grpcio-tools

  run:
    - python >={{ MIN_PYTHON_VERSION }}
    - typing-extensions
    - protobuf
    - grpcio
    - numpy
    - nanover-essd =={{ NANOVER_BUILD_VERSION }}

about:
  home: {{ NANOVER_DOC_URL }}
  license: MIT
  license_file: {{ NANOVER_LICENSE_PATH }}
  summary: Core modules to use the NanoVer python library.
  description: |
    NanoVer is a framework for interactive molecular dynamics simulation in
    virtual reality. This package provides the core components to write a
    server or a client program in python.
  doc_url: {{ NANOVER_DOC_URL }}
  dev_url: {{ NANOVER_REPO_URL }}
