# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/delimiter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/delimiter.proto',
  package='narupa.protocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fnarupa/protocol/delimiter.proto\x12\x0fnarupa.protocol*,\n\tDelimiter\x12\x0b\n\x07INVALID\x10\x00\x12\t\n\x05START\x10\x01\x12\x07\n\x03\x45ND\x10\x02\x62\x06proto3')
)

_DELIMITER = _descriptor.EnumDescriptor(
  name='Delimiter',
  full_name='narupa.protocol.Delimiter',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='END', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=52,
  serialized_end=96,
)
_sym_db.RegisterEnumDescriptor(_DELIMITER)

Delimiter = enum_type_wrapper.EnumTypeWrapper(_DELIMITER)
INVALID = 0
START = 1
END = 2


DESCRIPTOR.enum_types_by_name['Delimiter'] = _DELIMITER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
