# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/selection/AddSelection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from narupa.protocol.selection import AtomSelection_pb2 as narupa_dot_protocol_dot_selection_dot_AtomSelection__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/selection/AddSelection.proto',
  package='narupa.protocol.selection',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,narupa/protocol/selection/AddSelection.proto\x12\x19narupa.protocol.selection\x1a-narupa/protocol/selection/AtomSelection.proto\"}\n\x13\x41\x64\x64SelectionRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x14\n\x0cselection_id\x18\x02 \x01(\t\x12;\n\tselection\x18\x03 \x01(\x0b\x32(.narupa.protocol.selection.AtomSelection\"A\n\x14\x41\x64\x64SelectionResponse\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x14\n\x0cselection_id\x18\x02 \x01(\tb\x06proto3')
  ,
  dependencies=[narupa_dot_protocol_dot_selection_dot_AtomSelection__pb2.DESCRIPTOR,])




_ADDSELECTIONREQUEST = _descriptor.Descriptor(
  name='AddSelectionRequest',
  full_name='narupa.protocol.selection.AddSelectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='narupa.protocol.selection.AddSelectionRequest.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='selection_id', full_name='narupa.protocol.selection.AddSelectionRequest.selection_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='selection', full_name='narupa.protocol.selection.AddSelectionRequest.selection', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=247,
)


_ADDSELECTIONRESPONSE = _descriptor.Descriptor(
  name='AddSelectionResponse',
  full_name='narupa.protocol.selection.AddSelectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='narupa.protocol.selection.AddSelectionResponse.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='selection_id', full_name='narupa.protocol.selection.AddSelectionResponse.selection_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=314,
)

_ADDSELECTIONREQUEST.fields_by_name['selection'].message_type = narupa_dot_protocol_dot_selection_dot_AtomSelection__pb2._ATOMSELECTION
DESCRIPTOR.message_types_by_name['AddSelectionRequest'] = _ADDSELECTIONREQUEST
DESCRIPTOR.message_types_by_name['AddSelectionResponse'] = _ADDSELECTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddSelectionRequest = _reflection.GeneratedProtocolMessageType('AddSelectionRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDSELECTIONREQUEST,
  __module__ = 'narupa.protocol.selection.AddSelection_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.selection.AddSelectionRequest)
  ))
_sym_db.RegisterMessage(AddSelectionRequest)

AddSelectionResponse = _reflection.GeneratedProtocolMessageType('AddSelectionResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDSELECTIONRESPONSE,
  __module__ = 'narupa.protocol.selection.AddSelection_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.selection.AddSelectionResponse)
  ))
_sym_db.RegisterMessage(AddSelectionResponse)


# @@protoc_insertion_point(module_scope)
