# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/selection/RemoveSelection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/selection/RemoveSelection.proto',
  package='narupa.protocol.selection',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n/narupa/protocol/selection/RemoveSelection.proto\x12\x19narupa.protocol.selection\"C\n\x16RemoveSelectionRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x14\n\x0cselection_id\x18\x02 \x01(\t\"\x19\n\x17RemoveSelectionResponseb\x06proto3')
)




_REMOVESELECTIONREQUEST = _descriptor.Descriptor(
  name='RemoveSelectionRequest',
  full_name='narupa.protocol.selection.RemoveSelectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='narupa.protocol.selection.RemoveSelectionRequest.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='selection_id', full_name='narupa.protocol.selection.RemoveSelectionRequest.selection_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=145,
)


_REMOVESELECTIONRESPONSE = _descriptor.Descriptor(
  name='RemoveSelectionResponse',
  full_name='narupa.protocol.selection.RemoveSelectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=172,
)

DESCRIPTOR.message_types_by_name['RemoveSelectionRequest'] = _REMOVESELECTIONREQUEST
DESCRIPTOR.message_types_by_name['RemoveSelectionResponse'] = _REMOVESELECTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RemoveSelectionRequest = _reflection.GeneratedProtocolMessageType('RemoveSelectionRequest', (_message.Message,), dict(
  DESCRIPTOR = _REMOVESELECTIONREQUEST,
  __module__ = 'narupa.protocol.selection.RemoveSelection_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.selection.RemoveSelectionRequest)
  ))
_sym_db.RegisterMessage(RemoveSelectionRequest)

RemoveSelectionResponse = _reflection.GeneratedProtocolMessageType('RemoveSelectionResponse', (_message.Message,), dict(
  DESCRIPTOR = _REMOVESELECTIONRESPONSE,
  __module__ = 'narupa.protocol.selection.RemoveSelection_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.selection.RemoveSelectionResponse)
  ))
_sym_db.RegisterMessage(RemoveSelectionResponse)


# @@protoc_insertion_point(module_scope)
