# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/selection/Indices.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from narupa.protocol.selection import IndexList_pb2 as narupa_dot_protocol_dot_selection_dot_IndexList__pb2
from narupa.protocol.selection import IndexRange_pb2 as narupa_dot_protocol_dot_selection_dot_IndexRange__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/selection/Indices.proto',
  package='narupa.protocol.selection',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'narupa/protocol/selection/Indices.proto\x12\x19narupa.protocol.selection\x1a)narupa/protocol/selection/IndexList.proto\x1a*narupa/protocol/selection/IndexRange.proto\"\x8e\x01\n\x07Indices\x12:\n\nindex_list\x18\x01 \x01(\x0b\x32$.narupa.protocol.selection.IndexListH\x00\x12<\n\x0bindex_range\x18\x02 \x01(\x0b\x32%.narupa.protocol.selection.IndexRangeH\x00\x42\t\n\x07indicesb\x06proto3')
  ,
  dependencies=[narupa_dot_protocol_dot_selection_dot_IndexList__pb2.DESCRIPTOR,narupa_dot_protocol_dot_selection_dot_IndexRange__pb2.DESCRIPTOR,])




_INDICES = _descriptor.Descriptor(
  name='Indices',
  full_name='narupa.protocol.selection.Indices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index_list', full_name='narupa.protocol.selection.Indices.index_list', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index_range', full_name='narupa.protocol.selection.Indices.index_range', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='indices', full_name='narupa.protocol.selection.Indices.indices',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=158,
  serialized_end=300,
)

_INDICES.fields_by_name['index_list'].message_type = narupa_dot_protocol_dot_selection_dot_IndexList__pb2._INDEXLIST
_INDICES.fields_by_name['index_range'].message_type = narupa_dot_protocol_dot_selection_dot_IndexRange__pb2._INDEXRANGE
_INDICES.oneofs_by_name['indices'].fields.append(
  _INDICES.fields_by_name['index_list'])
_INDICES.fields_by_name['index_list'].containing_oneof = _INDICES.oneofs_by_name['indices']
_INDICES.oneofs_by_name['indices'].fields.append(
  _INDICES.fields_by_name['index_range'])
_INDICES.fields_by_name['index_range'].containing_oneof = _INDICES.oneofs_by_name['indices']
DESCRIPTOR.message_types_by_name['Indices'] = _INDICES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Indices = _reflection.GeneratedProtocolMessageType('Indices', (_message.Message,), dict(
  DESCRIPTOR = _INDICES,
  __module__ = 'narupa.protocol.selection.Indices_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.selection.Indices)
  ))
_sym_db.RegisterMessage(Indices)


# @@protoc_insertion_point(module_scope)
