# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from narupa.protocol.selection import AddSelection_pb2 as narupa_dot_protocol_dot_selection_dot_AddSelection__pb2
from narupa.protocol.selection import RemoveSelection_pb2 as narupa_dot_protocol_dot_selection_dot_RemoveSelection__pb2
from narupa.protocol.selection import SetSelection_pb2 as narupa_dot_protocol_dot_selection_dot_SetSelection__pb2


class SelectionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddSelection = channel.unary_unary(
        '/narupa.protocol.selection.SelectionService/AddSelection',
        request_serializer=narupa_dot_protocol_dot_selection_dot_AddSelection__pb2.AddSelectionRequest.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_selection_dot_AddSelection__pb2.AddSelectionResponse.FromString,
        )
    self.RemoveSelection = channel.unary_unary(
        '/narupa.protocol.selection.SelectionService/RemoveSelection',
        request_serializer=narupa_dot_protocol_dot_selection_dot_RemoveSelection__pb2.RemoveSelectionRequest.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_selection_dot_RemoveSelection__pb2.RemoveSelectionResponse.FromString,
        )
    self.SetSelection = channel.unary_unary(
        '/narupa.protocol.selection.SelectionService/SetSelection',
        request_serializer=narupa_dot_protocol_dot_selection_dot_SetSelection__pb2.SetSelectionRequest.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_selection_dot_SetSelection__pb2.SetSelectionResponse.FromString,
        )


class SelectionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddSelection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveSelection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetSelection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SelectionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddSelection': grpc.unary_unary_rpc_method_handler(
          servicer.AddSelection,
          request_deserializer=narupa_dot_protocol_dot_selection_dot_AddSelection__pb2.AddSelectionRequest.FromString,
          response_serializer=narupa_dot_protocol_dot_selection_dot_AddSelection__pb2.AddSelectionResponse.SerializeToString,
      ),
      'RemoveSelection': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveSelection,
          request_deserializer=narupa_dot_protocol_dot_selection_dot_RemoveSelection__pb2.RemoveSelectionRequest.FromString,
          response_serializer=narupa_dot_protocol_dot_selection_dot_RemoveSelection__pb2.RemoveSelectionResponse.SerializeToString,
      ),
      'SetSelection': grpc.unary_unary_rpc_method_handler(
          servicer.SetSelection,
          request_deserializer=narupa_dot_protocol_dot_selection_dot_SetSelection__pb2.SetSelectionRequest.FromString,
          response_serializer=narupa_dot_protocol_dot_selection_dot_SetSelection__pb2.SetSelectionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'narupa.protocol.selection.SelectionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
