# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/selection/SelectionService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from narupa.protocol.selection import AddSelection_pb2 as narupa_dot_protocol_dot_selection_dot_AddSelection__pb2
from narupa.protocol.selection import RemoveSelection_pb2 as narupa_dot_protocol_dot_selection_dot_RemoveSelection__pb2
from narupa.protocol.selection import SetSelection_pb2 as narupa_dot_protocol_dot_selection_dot_SetSelection__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/selection/SelectionService.proto',
  package='narupa.protocol.selection',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n0narupa/protocol/selection/SelectionService.proto\x12\x19narupa.protocol.selection\x1a,narupa/protocol/selection/AddSelection.proto\x1a/narupa/protocol/selection/RemoveSelection.proto\x1a,narupa/protocol/selection/SetSelection.proto2\xee\x02\n\x10SelectionService\x12o\n\x0c\x41\x64\x64Selection\x12..narupa.protocol.selection.AddSelectionRequest\x1a/.narupa.protocol.selection.AddSelectionResponse\x12x\n\x0fRemoveSelection\x12\x31.narupa.protocol.selection.RemoveSelectionRequest\x1a\x32.narupa.protocol.selection.RemoveSelectionResponse\x12o\n\x0cSetSelection\x12..narupa.protocol.selection.SetSelectionRequest\x1a/.narupa.protocol.selection.SetSelectionResponseb\x06proto3')
  ,
  dependencies=[narupa_dot_protocol_dot_selection_dot_AddSelection__pb2.DESCRIPTOR,narupa_dot_protocol_dot_selection_dot_RemoveSelection__pb2.DESCRIPTOR,narupa_dot_protocol_dot_selection_dot_SetSelection__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SELECTIONSERVICE = _descriptor.ServiceDescriptor(
  name='SelectionService',
  full_name='narupa.protocol.selection.SelectionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=221,
  serialized_end=587,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddSelection',
    full_name='narupa.protocol.selection.SelectionService.AddSelection',
    index=0,
    containing_service=None,
    input_type=narupa_dot_protocol_dot_selection_dot_AddSelection__pb2._ADDSELECTIONREQUEST,
    output_type=narupa_dot_protocol_dot_selection_dot_AddSelection__pb2._ADDSELECTIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveSelection',
    full_name='narupa.protocol.selection.SelectionService.RemoveSelection',
    index=1,
    containing_service=None,
    input_type=narupa_dot_protocol_dot_selection_dot_RemoveSelection__pb2._REMOVESELECTIONREQUEST,
    output_type=narupa_dot_protocol_dot_selection_dot_RemoveSelection__pb2._REMOVESELECTIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetSelection',
    full_name='narupa.protocol.selection.SelectionService.SetSelection',
    index=2,
    containing_service=None,
    input_type=narupa_dot_protocol_dot_selection_dot_SetSelection__pb2._SETSELECTIONREQUEST,
    output_type=narupa_dot_protocol_dot_selection_dot_SetSelection__pb2._SETSELECTIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SELECTIONSERVICE)

DESCRIPTOR.services_by_name['SelectionService'] = _SELECTIONSERVICE

# @@protoc_insertion_point(module_scope)
