# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/selection/VmdSelector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/selection/VmdSelector.proto',
  package='narupa.protocol.selection',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+narupa/protocol/selection/VmdSelector.proto\x12\x19narupa.protocol.selection\"\x1f\n\x0bVmdSelector\x12\x10\n\x08selector\x18\x01 \x01(\tb\x06proto3')
)




_VMDSELECTOR = _descriptor.Descriptor(
  name='VmdSelector',
  full_name='narupa.protocol.selection.VmdSelector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='selector', full_name='narupa.protocol.selection.VmdSelector.selector', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['VmdSelector'] = _VMDSELECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VmdSelector = _reflection.GeneratedProtocolMessageType('VmdSelector', (_message.Message,), dict(
  DESCRIPTOR = _VMDSELECTOR,
  __module__ = 'narupa.protocol.selection.VmdSelector_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.selection.VmdSelector)
  ))
_sym_db.RegisterMessage(VmdSelector)


# @@protoc_insertion_point(module_scope)
