# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/multiplayer/async_test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/multiplayer/async_test.proto',
  package='narupa.multiplayer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,narupa/protocol/multiplayer/async_test.proto\x12\x12narupa.multiplayer\x1a\x1cgoogle/protobuf/struct.proto\"\t\n\x07Request\"\x17\n\x08Response\x12\x0b\n\x03num\x18\x01 \x01(\x05\x32T\n\x04Test\x12L\n\x0b\x44oSomething\x12\x1b.narupa.multiplayer.Request\x1a\x1c.narupa.multiplayer.Response\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='narupa.multiplayer.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=107,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='narupa.multiplayer.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='narupa.multiplayer.Response.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'narupa.protocol.multiplayer.async_test_pb2'
  # @@protoc_insertion_point(class_scope:narupa.multiplayer.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'narupa.protocol.multiplayer.async_test_pb2'
  # @@protoc_insertion_point(class_scope:narupa.multiplayer.Response)
  ))
_sym_db.RegisterMessage(Response)



_TEST = _descriptor.ServiceDescriptor(
  name='Test',
  full_name='narupa.multiplayer.Test',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=134,
  serialized_end=218,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoSomething',
    full_name='narupa.multiplayer.Test.DoSomething',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEST)

DESCRIPTOR.services_by_name['Test'] = _TEST

# @@protoc_insertion_point(module_scope)
