# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/topology/TopologyInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from narupa.protocol.topology import AtomInfo_pb2 as narupa_dot_protocol_dot_topology_dot_AtomInfo__pb2
from narupa.protocol.topology import ChainInfo_pb2 as narupa_dot_protocol_dot_topology_dot_ChainInfo__pb2
from narupa.protocol.topology import BondPair_pb2 as narupa_dot_protocol_dot_topology_dot_BondPair__pb2
from narupa.protocol.topology import ResidueInfo_pb2 as narupa_dot_protocol_dot_topology_dot_ResidueInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/topology/TopologyInfo.proto',
  package='narupa.protocol.topology',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+narupa/protocol/topology/TopologyInfo.proto\x12\x18narupa.protocol.topology\x1a\'narupa/protocol/topology/AtomInfo.proto\x1a(narupa/protocol/topology/ChainInfo.proto\x1a\'narupa/protocol/topology/BondPair.proto\x1a*narupa/protocol/topology/ResidueInfo.proto\"\xe2\x01\n\x0cTopologyInfo\x12\x33\n\x06\x63hains\x18\x01 \x03(\x0b\x32#.narupa.protocol.topology.ChainInfo\x12\x37\n\x08residues\x18\x02 \x03(\x0b\x32%.narupa.protocol.topology.ResidueInfo\x12\x31\n\x05\x61toms\x18\x03 \x03(\x0b\x32\".narupa.protocol.topology.AtomInfo\x12\x31\n\x05\x62onds\x18\x04 \x03(\x0b\x32\".narupa.protocol.topology.BondPairb\x06proto3')
  ,
  dependencies=[narupa_dot_protocol_dot_topology_dot_AtomInfo__pb2.DESCRIPTOR,narupa_dot_protocol_dot_topology_dot_ChainInfo__pb2.DESCRIPTOR,narupa_dot_protocol_dot_topology_dot_BondPair__pb2.DESCRIPTOR,narupa_dot_protocol_dot_topology_dot_ResidueInfo__pb2.DESCRIPTOR,])




_TOPOLOGYINFO = _descriptor.Descriptor(
  name='TopologyInfo',
  full_name='narupa.protocol.topology.TopologyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chains', full_name='narupa.protocol.topology.TopologyInfo.chains', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='residues', full_name='narupa.protocol.topology.TopologyInfo.residues', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='atoms', full_name='narupa.protocol.topology.TopologyInfo.atoms', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bonds', full_name='narupa.protocol.topology.TopologyInfo.bonds', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=468,
)

_TOPOLOGYINFO.fields_by_name['chains'].message_type = narupa_dot_protocol_dot_topology_dot_ChainInfo__pb2._CHAININFO
_TOPOLOGYINFO.fields_by_name['residues'].message_type = narupa_dot_protocol_dot_topology_dot_ResidueInfo__pb2._RESIDUEINFO
_TOPOLOGYINFO.fields_by_name['atoms'].message_type = narupa_dot_protocol_dot_topology_dot_AtomInfo__pb2._ATOMINFO
_TOPOLOGYINFO.fields_by_name['bonds'].message_type = narupa_dot_protocol_dot_topology_dot_BondPair__pb2._BONDPAIR
DESCRIPTOR.message_types_by_name['TopologyInfo'] = _TOPOLOGYINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TopologyInfo = _reflection.GeneratedProtocolMessageType('TopologyInfo', (_message.Message,), dict(
  DESCRIPTOR = _TOPOLOGYINFO,
  __module__ = 'narupa.protocol.topology.TopologyInfo_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.topology.TopologyInfo)
  ))
_sym_db.RegisterMessage(TopologyInfo)


# @@protoc_insertion_point(module_scope)
