# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/instance/GetInstances.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from narupa.protocol.instance import InstanceInfo_pb2 as narupa_dot_protocol_dot_instance_dot_InstanceInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/instance/GetInstances.proto',
  package='narupa.protocol.instance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+narupa/protocol/instance/GetInstances.proto\x12\x18narupa.protocol.instance\x1a+narupa/protocol/instance/InstanceInfo.proto\"\x15\n\x13GetInstancesRequest\"Q\n\x14GetInstancesResponse\x12\x39\n\tinstances\x18\x01 \x03(\x0b\x32&.narupa.protocol.instance.InstanceInfob\x06proto3')
  ,
  dependencies=[narupa_dot_protocol_dot_instance_dot_InstanceInfo__pb2.DESCRIPTOR,])




_GETINSTANCESREQUEST = _descriptor.Descriptor(
  name='GetInstancesRequest',
  full_name='narupa.protocol.instance.GetInstancesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=139,
)


_GETINSTANCESRESPONSE = _descriptor.Descriptor(
  name='GetInstancesResponse',
  full_name='narupa.protocol.instance.GetInstancesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instances', full_name='narupa.protocol.instance.GetInstancesResponse.instances', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=222,
)

_GETINSTANCESRESPONSE.fields_by_name['instances'].message_type = narupa_dot_protocol_dot_instance_dot_InstanceInfo__pb2._INSTANCEINFO
DESCRIPTOR.message_types_by_name['GetInstancesRequest'] = _GETINSTANCESREQUEST
DESCRIPTOR.message_types_by_name['GetInstancesResponse'] = _GETINSTANCESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetInstancesRequest = _reflection.GeneratedProtocolMessageType('GetInstancesRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETINSTANCESREQUEST,
  __module__ = 'narupa.protocol.instance.GetInstances_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.GetInstancesRequest)
  ))
_sym_db.RegisterMessage(GetInstancesRequest)

GetInstancesResponse = _reflection.GeneratedProtocolMessageType('GetInstancesResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETINSTANCESRESPONSE,
  __module__ = 'narupa.protocol.instance.GetInstances_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.GetInstancesResponse)
  ))
_sym_db.RegisterMessage(GetInstancesResponse)


# @@protoc_insertion_point(module_scope)
