# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/instance/GetInstanceAtomCount.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/instance/GetInstanceAtomCount.proto',
  package='narupa.protocol.instance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n3narupa/protocol/instance/GetInstanceAtomCount.proto\x12\x18narupa.protocol.instance\"2\n\x1bGetInstanceAtomCountRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\"G\n\x1cGetInstanceAtomCountResponse\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x12\n\natom_count\x18\x02 \x01(\rb\x06proto3')
)




_GETINSTANCEATOMCOUNTREQUEST = _descriptor.Descriptor(
  name='GetInstanceAtomCountRequest',
  full_name='narupa.protocol.instance.GetInstanceAtomCountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='narupa.protocol.instance.GetInstanceAtomCountRequest.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=131,
)


_GETINSTANCEATOMCOUNTRESPONSE = _descriptor.Descriptor(
  name='GetInstanceAtomCountResponse',
  full_name='narupa.protocol.instance.GetInstanceAtomCountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='narupa.protocol.instance.GetInstanceAtomCountResponse.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='atom_count', full_name='narupa.protocol.instance.GetInstanceAtomCountResponse.atom_count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=204,
)

DESCRIPTOR.message_types_by_name['GetInstanceAtomCountRequest'] = _GETINSTANCEATOMCOUNTREQUEST
DESCRIPTOR.message_types_by_name['GetInstanceAtomCountResponse'] = _GETINSTANCEATOMCOUNTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetInstanceAtomCountRequest = _reflection.GeneratedProtocolMessageType('GetInstanceAtomCountRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETINSTANCEATOMCOUNTREQUEST,
  __module__ = 'narupa.protocol.instance.GetInstanceAtomCount_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.GetInstanceAtomCountRequest)
  ))
_sym_db.RegisterMessage(GetInstanceAtomCountRequest)

GetInstanceAtomCountResponse = _reflection.GeneratedProtocolMessageType('GetInstanceAtomCountResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETINSTANCEATOMCOUNTRESPONSE,
  __module__ = 'narupa.protocol.instance.GetInstanceAtomCount_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.GetInstanceAtomCountResponse)
  ))
_sym_db.RegisterMessage(GetInstanceAtomCountResponse)


# @@protoc_insertion_point(module_scope)
