# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from narupa.protocol.instance import instance_service_pb2 as narupa_dot_protocol_dot_instance_dot_instance__service__pb2


class InstanceServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.LoadTrajectory = channel.unary_unary(
        '/narupa.protocol.instance.InstanceService/LoadTrajectory',
        request_serializer=narupa_dot_protocol_dot_instance_dot_instance__service__pb2.LoadTrajectoryRequest.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_instance_dot_instance__service__pb2.LoadTrajectoryResponse.FromString,
        )
    self.GetInstanceInfo = channel.unary_unary(
        '/narupa.protocol.instance.InstanceService/GetInstanceInfo',
        request_serializer=narupa_dot_protocol_dot_instance_dot_instance__service__pb2.GetInstanceInfoRequest.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_instance_dot_instance__service__pb2.GetInstanceInfoResponse.FromString,
        )
    self.CloseInstance = channel.unary_unary(
        '/narupa.protocol.instance.InstanceService/CloseInstance',
        request_serializer=narupa_dot_protocol_dot_instance_dot_instance__service__pb2.CloseInstanceRequest.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_instance_dot_instance__service__pb2.CloseInstanceResponse.FromString,
        )


class InstanceServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def LoadTrajectory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetInstanceInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CloseInstance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InstanceServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'LoadTrajectory': grpc.unary_unary_rpc_method_handler(
          servicer.LoadTrajectory,
          request_deserializer=narupa_dot_protocol_dot_instance_dot_instance__service__pb2.LoadTrajectoryRequest.FromString,
          response_serializer=narupa_dot_protocol_dot_instance_dot_instance__service__pb2.LoadTrajectoryResponse.SerializeToString,
      ),
      'GetInstanceInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetInstanceInfo,
          request_deserializer=narupa_dot_protocol_dot_instance_dot_instance__service__pb2.GetInstanceInfoRequest.FromString,
          response_serializer=narupa_dot_protocol_dot_instance_dot_instance__service__pb2.GetInstanceInfoResponse.SerializeToString,
      ),
      'CloseInstance': grpc.unary_unary_rpc_method_handler(
          servicer.CloseInstance,
          request_deserializer=narupa_dot_protocol_dot_instance_dot_instance__service__pb2.CloseInstanceRequest.FromString,
          response_serializer=narupa_dot_protocol_dot_instance_dot_instance__service__pb2.CloseInstanceResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'narupa.protocol.instance.InstanceService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
