# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/instance/instance_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/instance/instance_service.proto',
  package='narupa.protocol.instance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n/narupa/protocol/instance/instance_service.proto\x12\x18narupa.protocol.instance\x1a\x1cgoogle/protobuf/struct.proto\x1a google/protobuf/field_mask.proto\":\n\x15LoadTrajectoryRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"-\n\x16LoadTrajectoryResponse\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\"Y\n\x16GetInstanceInfoRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12*\n\x06\x66ields\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\"U\n\x17GetInstanceInfoResponse\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12%\n\x04info\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"+\n\x14\x43loseInstanceRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\",\n\x15\x43loseInstanceResponse\x12\x13\n\x0binstance_id\x18\x01 \x01(\t2\xf0\x02\n\x0fInstanceService\x12s\n\x0eLoadTrajectory\x12/.narupa.protocol.instance.LoadTrajectoryRequest\x1a\x30.narupa.protocol.instance.LoadTrajectoryResponse\x12v\n\x0fGetInstanceInfo\x12\x30.narupa.protocol.instance.GetInstanceInfoRequest\x1a\x31.narupa.protocol.instance.GetInstanceInfoResponse\x12p\n\rCloseInstance\x12..narupa.protocol.instance.CloseInstanceRequest\x1a/.narupa.protocol.instance.CloseInstanceResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,google_dot_protobuf_dot_field__mask__pb2.DESCRIPTOR,])




_LOADTRAJECTORYREQUEST = _descriptor.Descriptor(
  name='LoadTrajectoryRequest',
  full_name='narupa.protocol.instance.LoadTrajectoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='narupa.protocol.instance.LoadTrajectoryRequest.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='narupa.protocol.instance.LoadTrajectoryRequest.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=199,
)


_LOADTRAJECTORYRESPONSE = _descriptor.Descriptor(
  name='LoadTrajectoryResponse',
  full_name='narupa.protocol.instance.LoadTrajectoryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='narupa.protocol.instance.LoadTrajectoryResponse.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=246,
)


_GETINSTANCEINFOREQUEST = _descriptor.Descriptor(
  name='GetInstanceInfoRequest',
  full_name='narupa.protocol.instance.GetInstanceInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='narupa.protocol.instance.GetInstanceInfoRequest.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fields', full_name='narupa.protocol.instance.GetInstanceInfoRequest.fields', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=337,
)


_GETINSTANCEINFORESPONSE = _descriptor.Descriptor(
  name='GetInstanceInfoResponse',
  full_name='narupa.protocol.instance.GetInstanceInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='narupa.protocol.instance.GetInstanceInfoResponse.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='narupa.protocol.instance.GetInstanceInfoResponse.info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=424,
)


_CLOSEINSTANCEREQUEST = _descriptor.Descriptor(
  name='CloseInstanceRequest',
  full_name='narupa.protocol.instance.CloseInstanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='narupa.protocol.instance.CloseInstanceRequest.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=469,
)


_CLOSEINSTANCERESPONSE = _descriptor.Descriptor(
  name='CloseInstanceResponse',
  full_name='narupa.protocol.instance.CloseInstanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='narupa.protocol.instance.CloseInstanceResponse.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=515,
)

_GETINSTANCEINFOREQUEST.fields_by_name['fields'].message_type = google_dot_protobuf_dot_field__mask__pb2._FIELDMASK
_GETINSTANCEINFORESPONSE.fields_by_name['info'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['LoadTrajectoryRequest'] = _LOADTRAJECTORYREQUEST
DESCRIPTOR.message_types_by_name['LoadTrajectoryResponse'] = _LOADTRAJECTORYRESPONSE
DESCRIPTOR.message_types_by_name['GetInstanceInfoRequest'] = _GETINSTANCEINFOREQUEST
DESCRIPTOR.message_types_by_name['GetInstanceInfoResponse'] = _GETINSTANCEINFORESPONSE
DESCRIPTOR.message_types_by_name['CloseInstanceRequest'] = _CLOSEINSTANCEREQUEST
DESCRIPTOR.message_types_by_name['CloseInstanceResponse'] = _CLOSEINSTANCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoadTrajectoryRequest = _reflection.GeneratedProtocolMessageType('LoadTrajectoryRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOADTRAJECTORYREQUEST,
  __module__ = 'narupa.protocol.instance.instance_service_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.LoadTrajectoryRequest)
  ))
_sym_db.RegisterMessage(LoadTrajectoryRequest)

LoadTrajectoryResponse = _reflection.GeneratedProtocolMessageType('LoadTrajectoryResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOADTRAJECTORYRESPONSE,
  __module__ = 'narupa.protocol.instance.instance_service_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.LoadTrajectoryResponse)
  ))
_sym_db.RegisterMessage(LoadTrajectoryResponse)

GetInstanceInfoRequest = _reflection.GeneratedProtocolMessageType('GetInstanceInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETINSTANCEINFOREQUEST,
  __module__ = 'narupa.protocol.instance.instance_service_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.GetInstanceInfoRequest)
  ))
_sym_db.RegisterMessage(GetInstanceInfoRequest)

GetInstanceInfoResponse = _reflection.GeneratedProtocolMessageType('GetInstanceInfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETINSTANCEINFORESPONSE,
  __module__ = 'narupa.protocol.instance.instance_service_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.GetInstanceInfoResponse)
  ))
_sym_db.RegisterMessage(GetInstanceInfoResponse)

CloseInstanceRequest = _reflection.GeneratedProtocolMessageType('CloseInstanceRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLOSEINSTANCEREQUEST,
  __module__ = 'narupa.protocol.instance.instance_service_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.CloseInstanceRequest)
  ))
_sym_db.RegisterMessage(CloseInstanceRequest)

CloseInstanceResponse = _reflection.GeneratedProtocolMessageType('CloseInstanceResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLOSEINSTANCERESPONSE,
  __module__ = 'narupa.protocol.instance.instance_service_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.CloseInstanceResponse)
  ))
_sym_db.RegisterMessage(CloseInstanceResponse)



_INSTANCESERVICE = _descriptor.ServiceDescriptor(
  name='InstanceService',
  full_name='narupa.protocol.instance.InstanceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=518,
  serialized_end=886,
  methods=[
  _descriptor.MethodDescriptor(
    name='LoadTrajectory',
    full_name='narupa.protocol.instance.InstanceService.LoadTrajectory',
    index=0,
    containing_service=None,
    input_type=_LOADTRAJECTORYREQUEST,
    output_type=_LOADTRAJECTORYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetInstanceInfo',
    full_name='narupa.protocol.instance.InstanceService.GetInstanceInfo',
    index=1,
    containing_service=None,
    input_type=_GETINSTANCEINFOREQUEST,
    output_type=_GETINSTANCEINFORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CloseInstance',
    full_name='narupa.protocol.instance.InstanceService.CloseInstance',
    index=2,
    containing_service=None,
    input_type=_CLOSEINSTANCEREQUEST,
    output_type=_CLOSEINSTANCERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INSTANCESERVICE)

DESCRIPTOR.services_by_name['InstanceService'] = _INSTANCESERVICE

# @@protoc_insertion_point(module_scope)
