# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from narupa.protocol.instance import representation_service_pb2 as narupa_dot_protocol_dot_instance_dot_representation__service__pb2


class RepresentationServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SetRepresentation = channel.unary_unary(
        '/narupa.protocol.instance.RepresentationService/SetRepresentation',
        request_serializer=narupa_dot_protocol_dot_instance_dot_representation__service__pb2.SetRepresentationRequest.SerializeToString,
        response_deserializer=narupa_dot_protocol_dot_instance_dot_representation__service__pb2.SetRepresentationResponse.FromString,
        )


class RepresentationServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SetRepresentation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RepresentationServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SetRepresentation': grpc.unary_unary_rpc_method_handler(
          servicer.SetRepresentation,
          request_deserializer=narupa_dot_protocol_dot_instance_dot_representation__service__pb2.SetRepresentationRequest.FromString,
          response_serializer=narupa_dot_protocol_dot_instance_dot_representation__service__pb2.SetRepresentationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'narupa.protocol.instance.RepresentationService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
