# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: narupa/protocol/instance/representation_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='narupa/protocol/instance/representation_service.proto',
  package='narupa.protocol.instance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n5narupa/protocol/instance/representation_service.proto\x12\x18narupa.protocol.instance\x1a\x1cgoogle/protobuf/struct.proto\x1a google/protobuf/field_mask.proto\"v\n\x18SetRepresentationRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x14\n\x0cselection_id\x18\x02 \x01(\t\x12/\n\x0erepresentation\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"0\n\x19SetRepresentationResponse\x12\x13\n\x0binstance_id\x18\x01 \x01(\t2\x95\x01\n\x15RepresentationService\x12|\n\x11SetRepresentation\x12\x32.narupa.protocol.instance.SetRepresentationRequest\x1a\x33.narupa.protocol.instance.SetRepresentationResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,google_dot_protobuf_dot_field__mask__pb2.DESCRIPTOR,])




_SETREPRESENTATIONREQUEST = _descriptor.Descriptor(
  name='SetRepresentationRequest',
  full_name='narupa.protocol.instance.SetRepresentationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='narupa.protocol.instance.SetRepresentationRequest.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='selection_id', full_name='narupa.protocol.instance.SetRepresentationRequest.selection_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='representation', full_name='narupa.protocol.instance.SetRepresentationRequest.representation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=265,
)


_SETREPRESENTATIONRESPONSE = _descriptor.Descriptor(
  name='SetRepresentationResponse',
  full_name='narupa.protocol.instance.SetRepresentationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='narupa.protocol.instance.SetRepresentationResponse.instance_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=315,
)

_SETREPRESENTATIONREQUEST.fields_by_name['representation'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['SetRepresentationRequest'] = _SETREPRESENTATIONREQUEST
DESCRIPTOR.message_types_by_name['SetRepresentationResponse'] = _SETREPRESENTATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetRepresentationRequest = _reflection.GeneratedProtocolMessageType('SetRepresentationRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETREPRESENTATIONREQUEST,
  __module__ = 'narupa.protocol.instance.representation_service_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.SetRepresentationRequest)
  ))
_sym_db.RegisterMessage(SetRepresentationRequest)

SetRepresentationResponse = _reflection.GeneratedProtocolMessageType('SetRepresentationResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETREPRESENTATIONRESPONSE,
  __module__ = 'narupa.protocol.instance.representation_service_pb2'
  # @@protoc_insertion_point(class_scope:narupa.protocol.instance.SetRepresentationResponse)
  ))
_sym_db.RegisterMessage(SetRepresentationResponse)



_REPRESENTATIONSERVICE = _descriptor.ServiceDescriptor(
  name='RepresentationService',
  full_name='narupa.protocol.instance.RepresentationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=318,
  serialized_end=467,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetRepresentation',
    full_name='narupa.protocol.instance.RepresentationService.SetRepresentation',
    index=0,
    containing_service=None,
    input_type=_SETREPRESENTATIONREQUEST,
    output_type=_SETREPRESENTATIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPRESENTATIONSERVICE)

DESCRIPTOR.services_by_name['RepresentationService'] = _REPRESENTATIONSERVICE

# @@protoc_insertion_point(module_scope)
