on: [push]
name: "PyPI"

jobs:
  build-pypi:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # We need all the history to figure out the version number
      - name: Set environment variables
        run: |
          echo "0.1.$(git rev-list --count HEAD)" > ./python-libraries/nanover-server/VERSION.txt
      - name: Test that the repo is sane and does not contain superfluous __init__ file
        run: bash ./maintainers/check_extra_init_files.sh
      - name: Building the PyPI packages
        run: |
          pip install build
          python -m build ./python-libraries/nanover-server
      - run: |
          mkdir artifacts
          cp -r ./python-libraries/nanover-server/dist ./artifacts
          ls -1 ./artifacts/dist/*.tar.gz | xargs -L1 -I{} cp {} ./artifacts/dist/nanover_server.tar.gz 
          ls ./artifacts
      - name: Save the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pypi-packages
          path: ./artifacts
  test-pypi:
    name: Test package
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    continue-on-error: true
    needs: build-pypi
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v9.0.0
      - name: Retrieve PyPI packages
        uses: actions/download-artifact@v4
        with:
          name: pypi-packages
      - name: Install NanoVer
        run: |
          ls ./dist
          uv venv --python 3.14
          uv pip install ./dist/nanover_server.tar.gz
      - name: Install extra dependencies
        run: |
          uv pip install -r ./python-libraries/nanover-server/pyproject.toml --all-extras
#      - name: All tests
#        run: python -m pytest python-libraries --timeout 60
      - name: Parallel tests
        run: uv run pytest python-libraries -n auto -m 'not serial' --timeout 60
      - name: Serial tests
        run: uv run pytest python-libraries -n 1 -m 'serial' --timeout 60
  publish-pypi:
    name: Publish packages
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test-pypi
    environment:
      name: pypi
      url: https://pypi.org/p/nanover-server
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Retrieve PyPI packages
        uses: actions/download-artifact@v4
        with:
          name: pypi-packages
      - name: Remove windows hack
        run: |
          rm ./dist/nanover_server.tar.gz
          ls ./dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
