on: [push]
name: "Repo"

jobs:
  python-tests:
    name: Tests and Notebooks
    timeout-minutes: 15
    runs-on: ubuntu-latest
    defaults:
      run:
        # This is necessary for the conda action. It replaces `conda init` as
        # the shell does not load ,profile or .bashrc.
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: 3.14
          activate-environment: "true"
      - name: Install NanoVer & dependencies
        run: uv pip install ./[dev]
      - name: Parallel tests
        run: uv run pytest --cov nanover tests -n auto -m 'not serial' --timeout 30
      - name: Serial tests
        run: uv run pytest --cov nanover tests -n 1 -m 'serial' --cov-append --timeout 30
      - name: Jupyter notebooks
        run: uv run pytest --cov nanover --nbval-lax ./tutorials --nbval-cell-timeout=30 --cov-append
  python-tests-minimum:
    name: Tests and Notebooks (minimum versions)
    timeout-minutes: 15
    runs-on: ubuntu-latest
    defaults:
      run:
        # This is necessary for the conda action. It replaces `conda init` as
        # the shell does not load ,profile or .bashrc.
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: 3.13
          activate-environment: "true"
      - name: Install NanoVer & dependencies
        run: |
          uv pip install tomli-w
          uv pip install setuptools
          python ./maintainers/minimum-deps.py ./pyproject.toml
          uv pip install ./[dev]
      - name: Parallel tests
        run: pytest tests -n auto -m 'not serial' --timeout 30
      - name: Serial tests
        run: pytest tests -n 1 -m 'serial' --timeout 30
      - name: Jupyter notebooks
        run: pytest --nbval-lax ./tutorials --nbval-cell-timeout=30
  analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        # This is necessary for the conda action. It replaces `conda init` as
        # the shell does not load ,profile or .bashrc.
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: 3.14
          activate-environment: "true"
      - name: Install NanoVer & dependencies
        run: uv pip install ./[dev] ruff mypy
      - name: Ruff lint
        run: uv run ruff check ./src
      - name: Ruff format
        run: uv run ruff format --check ./src
      - name: mypy types
        run: |
          # Mypy accepts paths, modules or packages as inputs. However, only
          # packages work reasonably well with packages. So we need to generate
          # a list of the packages we want to test.
          packages=$(find . -name __init__.py \
            | sed 's/__init__.py//g' \
            | awk '{split($0, a, /src/); print(a[2])}' \
            | sed 's#/#.#g' \
            | cut -c 2- \
            | sed 's/\.$//g' \
            | grep -v '^$' \
            | grep -v protocol \
            | sed 's/^/-p /g' \
            | grep -v '\..*\.' \
            | tr '\n' ' ')
          echo "$packages"
          mypy --ignore-missing-imports --namespace-packages --check-untyped-defs --allow-redefinition $packages
